[package]
name = "TOP"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.18"
egui = "0.18"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"


